import 'package:audioplayers/audioplayers.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Plays/stops the alarm Ton (ADR 0017, "Ton") behind a small interface so
/// widget tests can substitute a fake instead of touching real audio.
abstract class AlarmSound {
  /// Starts playback, looping forever when [loop] is true. Calling this
  /// again while already playing restarts playback.
  Future<void> play({bool loop = false});

  /// Stops playback. A no-op when nothing is playing.
  Future<void> stop();
}

/// [AlarmSound] backed by `audioplayers`, playing the synthetic siren
/// asset generated by `tool/make_alarm.py`.
class AudioPlayerAlarmSound implements AlarmSound {
  AudioPlayerAlarmSound() : _player = AudioPlayer();

  final AudioPlayer _player;

  @override
  Future<void> play({bool loop = false}) async {
    await _player.setReleaseMode(
      loop ? ReleaseMode.loop : ReleaseMode.release,
    );
    await _player.play(AssetSource('sounds/alarm.wav'));
  }

  @override
  Future<void> stop() async {
    await _player.stop();
  }

  /// Releases the underlying player. Not part of [AlarmSound]: only the
  /// app-wide singleton created by [alarmSoundProvider] needs this, on
  /// `ProviderScope` disposal.
  Future<void> dispose() => _player.dispose();
}

/// App-wide [AlarmSound] singleton. Overridden with a fake in widget
/// tests.
final alarmSoundProvider = Provider<AlarmSound>((ref) {
  final sound = AudioPlayerAlarmSound();
  ref.onDispose(() {
    // Best-effort: dispose errors must never crash provider teardown.
    sound.dispose().catchError((_) {});
  });
  return sound;
});
